[package]
name = "epitaph"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["webgl", "web-colors", "fira-sans"] }
rfd = "0.16.0"

[profile.release]
debug = false
lto = true
opt-level = "z"
panic = 'abort'
codegen-units = 1